alias zshconfig='vi ~/.zshrc'
alias sourcezsh='source ~/.zshrc'
alias setzsh='chsh -s "$(which zsh)"'
alias setbash='chsh -s "$(which bash)"'
alias c='clear'
alias skills-lock='gh skill list --json skillName,sourceURL,scope,version,pinned,agentHosts > ~/.dotfiles/skills/skills.lock.json'
